#!/usr/bin/env bash
# THE OVERNIGHT CHAIN (2026-09-12 night, Sevan: "kick off the big run"). Two products:
#  A. the unified-protocol RESCORE — every listed run in both environments under the new edit
#     protocol (1000 cases, fixed edit position, per-instance benches, full-state writes, shared
#     alpha grids and GS layers, Othello headline = symmetric difference, discworld target = the
#     pre-dynamics state) + Table 3 alignment refresh + Haufe editability + Table 4 + both table
#     notebooks;
#  B. the anti-aliasing instance dw-smooth (generated by the separate CPU unit dw_smooth_gen,
#     scripts/drivers/dw_smooth_gen.sh): Transformer-L 780k under the matched recipe, then the
#     canonical frustum block, appearance-fac probes + both floors, scoring, tables.
#
# Launch (GPU must be free; nothing else may score or fit while it runs):
#   systemd-run --user --unit=rescore_protocol -p MemoryMax=45G --collect --working-directory=$PWD \
#       /usr/bin/bash -c 'bash scripts/drivers/rescore_2026-09-12.sh > logs/rescore_2026-09-12/unit.log 2>&1'
# Then arm the two monitors (harness/OVERNIGHT.md): a stage watcher on this driver.log + the unit's
# state, and a 30-min heartbeat (scored-file count during stage 2, metrics.jsonl during stage 7).
#
# Stages (each logged to logs/rescore_2026-09-12/, each pinged):
#   0  wait for unit dw_smooth_gen (corpus.json + edits/v1/selection.json present); ≤ 3 h
#   1  train.py --smoke on dw-smooth (200 steps into runs/_pipeline_smoke) — the corpus loads
#   2  master_eval — rescores every discworld run (EVAL_VERSION_BY_ENV discworld 2026-09-12.2)
#      and every Othello run (othello 2026-09-12.1) on the new benches; fits the canonical floors
#      of every scored instance (the baselines cell)
#   3  table3_alignment.py — refresh Table 3's alignment rows at the NEW best PI points
#   4  table3_haufe_edit.py — Table 3's PI-after-Haufe columns
#   5  test_loss.py — Table 4 refresh (cheap)
#   6  build_paper_tables + build_full_tables  → ping "RESCORE DONE" with the headline
#   7  train Transformer-L on dw-smooth, 780k steps (~8 h) → runs/smooth_ablation/L-dw-smooth-20m
#   8  appearance-fac probes on the new run: model, random-init floor, observation floor
#   9  master_eval again — scores the new run only (frustum + appearance-fac; frustum floors fitted)
#  10  test_loss + both table notebooks → ping "ALL DONE"
set -u
ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
PY=$ROOT/.pim/bin/python
LOGS=$ROOT/logs/rescore_2026-09-12
mkdir -p "$LOGS"
NT=https://ntfy.sh/swirling-tornado-ai691k
cd "$ROOT"

ping()  { curl -sS --max-time 20 -H "Title: $1" -H "Tags: ${3:-information_source}" -d "$2" "$NT" > /dev/null 2>&1 || true; }
stage() { echo "=== [$(date '+%F %T')] STAGE $* ===" | tee -a "$LOGS/driver.log"; }
fail()  { ping "PIM overnight FAILED: $1" "$2" warning; echo "FAILED: $1" >> "$LOGS/driver.log"; exit 1; }
nb()    { ( cd "$ROOT/notebooks" && "$PY" "$ROOT/.pim/bin/jupyter-nbconvert" --to notebook --execute --inplace "$1.ipynb" \
            --ExecutePreprocessor.timeout=57600 ) > "$LOGS/$2.log" 2>&1 || fail "$2" "$(tail -25 "$LOGS/$2.log")"; }

INST=dw-smooth
RUN_TOPIC=smooth_ablation
RUN_NAME=L-dw-smooth-20m
INST_DIR=$ROOT/datasets/discworld/$INST

ping "PIM overnight: chain started" "0 wait dw_smooth_gen → 1 smoke-train → 2 master_eval (both envs; ~9-11 h) → 3-6 alignment/Haufe/test-loss/tables [RESCORE DONE] → 7 train L-dw-smooth-20m (~8 h) → 8 fac probes → 9-10 score + tables [ALL DONE]." rocket

stage "0 wait for dw_smooth_gen"
WAITED=0
while st=$(systemctl --user is-active dw_smooth_gen 2>/dev/null); [ "$st" = "active" ] || [ "$st" = "activating" ]; do
  sleep 60; WAITED=$((WAITED + 1))
  if [ $WAITED -ge 180 ]; then fail "0 wait" "dw_smooth_gen still active after 3 h — not starting the chain"; fi
done
[ -f "$INST_DIR/train/corpus.json" ] || fail "0 wait" "dw_smooth_gen ended ($st) without train/corpus.json — see logs/smooth_ablation/dw_smooth_gen/"
[ -f "$INST_DIR/edits/v1/selection.json" ] || fail "0 wait" "dw_smooth_gen ended ($st) without edits/v1/selection.json"
echo "  dw_smooth_gen is $st; corpus.json + selection.json present" | tee -a "$LOGS/driver.log"

stage "1 smoke-train on dw-smooth"
"$PY" -u scripts/train.py --env discworld --arch transformer_l --instance "$INST" \
    --topic _pipeline_smoke --run-name dw-smooth-smoke --steps 200 --smoke \
    > "$LOGS/smoke_train.log" 2>&1 || fail "1 smoke-train" "$(tail -20 "$LOGS/smoke_train.log")"
ping "PIM overnight: smoke-train OK" "$(grep '^done' "$LOGS/smoke_train.log" | tail -1). master_eval starts now (~9-11 h)."

stage "2 master_eval (both environments)"
nb master_eval master_eval
N_NEW=$(grep -l '"eval_version": "2026-09-12' runs/*/*/scores.json 2>/dev/null | wc -l)
ping "PIM overnight: master_eval DONE" "$N_NEW scores.json at the new versions." white_check_mark

stage "3 Table 3 alignment refresh"
"$PY" -W ignore experiments/edit_direction_alignment/scripts/table3_alignment.py > "$LOGS/table3_alignment.log" 2>&1 \
    || fail "table3_alignment" "$(tail -15 "$LOGS/table3_alignment.log")"

stage "4 Table 3 Haufe editability"
"$PY" -W ignore experiments/edit_direction_alignment/scripts/table3_haufe_edit.py > "$LOGS/table3_haufe.log" 2>&1 \
    || fail "table3_haufe_edit" "$(tail -15 "$LOGS/table3_haufe.log")"
ping "PIM overnight: Haufe editability DONE" "$(grep -h 'PI-haufe' "$LOGS/table3_haufe.log" | head -16)"

stage "5 test loss"
"$PY" -W ignore experiments/bayes_floor/scripts/test_loss.py > "$LOGS/test_loss.log" 2>&1 || true

stage "6 tables"
nb build_paper_tables build_paper_tables
nb build_full_tables build_full_tables
"$PY" - > "$LOGS/headline.txt" 2>&1 <<'EOF'
import json, glob
for p in sorted(glob.glob("runs/*/*/scores.json")):
    if p.startswith("runs/_") or "/archive/" in p or "training_curve" in p: continue
    s = json.load(open(p))
    if not str(s.get("eval_version", "")).startswith("2026-09-12"): continue
    if s["env"] == "othello":
        u = s["unedited"]["edit_index_symdiff"]; b = {e: s["best"][e] for e in ("PI", "ND", "GS") if s["best"].get(e)}
        print(f"{s['run']:<46} uned {u:+.3f}  " + "  ".join(f"{e} {v['edit_index_symdiff']:+.3f}/{v['fidelity_ratio']:.2f}" for e, v in b.items()))
    else:
        T = s["bases"].get("frustum") or next(iter(s["bases"].values()))
        u = T["unedited"]["edit_index"]; b = {e: T["best"][e] for e in ("PI", "GS") if T["best"].get(e)}
        print(f"{s['run']:<46} uned {u:+.3f}  " + "  ".join(f"{e} {v['edit_index']:+.3f}/{v['fidelity_ratio']:.2f}" for e, v in b.items()))
EOF
ping "PIM overnight: RESCORE DONE" "$(head -30 "$LOGS/headline.txt")
Training L-dw-smooth-20m now (~8 h)." white_check_mark

stage "7 train $RUN_TOPIC/$RUN_NAME (GPU, 780k)"
"$PY" scripts/train.py --env discworld --arch transformer_l --instance "$INST" \
    --topic "$RUN_TOPIC" --run-name "$RUN_NAME" --steps 780000 \
    > "$LOGS/train_smooth.log" 2>&1 || fail "7 training" "$(tail -20 "$LOGS/train_smooth.log")"
ping "PIM overnight: dw-smooth training DONE" "$(grep '^done' "$LOGS/train_smooth.log" | tail -1)
appearance-fac probes + floors, then scoring (~1.5 h)." checkered_flag

stage "8 appearance-fac probes + floors"
fit() { local tag=$1; shift
        "$PY" -u scripts/fit_probes.py --run "$RUN_TOPIC/$RUN_NAME" --target appearance-fac "$@" \
            > "$LOGS/fit_fac_$tag.log" 2>&1 || fail "8 fit $tag" "$(tail -15 "$LOGS/fit_fac_$tag.log")"; }
fit model
fit random_init --random-init
fit observation --observation

stage "9 master_eval (the new run)"
nb master_eval master_eval_smooth

stage "10 test loss + tables"
"$PY" -W ignore experiments/bayes_floor/scripts/test_loss.py > "$LOGS/test_loss_2.log" 2>&1 || true
nb build_paper_tables build_paper_tables_2
nb build_full_tables build_full_tables_2
SCORES=$ROOT/runs/$RUN_TOPIC/$RUN_NAME/scores.json
ping "PIM overnight: ALL DONE" "$("$PY" - "$SCORES" <<'EOF2'
import json, sys
s = json.load(open(sys.argv[1]))
print(f"L-dw-smooth-20m  val {s['val_loss']:.5f}")
for basis, T in s["bases"].items():
    b = T["best"]
    print(f"{basis}: skill LIN {max(T['probe_skill_linear']):+.3f} MLP {max(T['probe_skill_mlp']):+.3f} | "
          f"unedited {T['unedited']['edit_index']:+.3f} | " +
          " ".join(f"{k} {v['edit_index']:+.3f}/{v['fidelity_ratio']:.2f}" for k, v in b.items() if v))
EOF2
)" white_check_mark
stage "chain complete"
